package com.myapp.struts;
// Generated Jan 22, 2015 2:15:19 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import org.apache.struts.upload.FormFile;

/**
 * Emp generated by hbm2java
 */
public class Emp extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int eid;
     private String ename;
     private String edesig;
     private int esal;
     private String edoj;
     private String eadd;
     private String filename;
     private FormFile theFile;

    public Emp() {
    }

	
    public Emp(short eid) {
        this.eid = eid;
    }
    public Emp(int eid, String ename, String edesig, int esal, String edoj, String eadd, String filename) {
       this.eid = eid;
       this.ename = ename;
       this.edesig = edesig;
       this.esal = esal;
       this.edoj = edoj;
       this.eadd = eadd;
       this.filename = filename;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getEdesig() {
        return this.edesig;
    }
    
    public void setEdesig(String edesig) {
        this.edesig = edesig;
    }
    public int getEsal() {
        return this.esal;
    }
    
    public void setEsal(int esal) {
        this.esal = esal;
    }
    public String getEdoj() {
        return this.edoj;
    }
    
    public void setEdoj(String edoj) {
        this.edoj = edoj;
    }
    public String getEadd() {
        return this.eadd;
    }
    
    public void setEadd(String eadd) {
        this.eadd = eadd;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * @return the theFile
     */
    public FormFile getTheFile() {
        return theFile;
    }

    /**
     * @param theFile the theFile to set
     */
    public void setTheFile(FormFile theFile) {
        this.theFile = theFile;
    }




}


