package com.myapp.struts;
// Generated Dec 14, 2015 12:53:38 PM by Hibernate Tools 3.2.1.GA

import org.apache.struts.upload.FormFile;




/**
 * Studreg generated by hbm2java
 */
public class Studreg extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String sname;
     private Studlog studlog;
     private String addr;
     private String eid;
     private String cno;
     private String photo;
     private FormFile photo1;

    public Studreg() {
    }

	
    public Studreg(String sname, Studlog studlog) {
        this.sname = sname;
        this.studlog = studlog;
    }
    public Studreg(String sname, Studlog studlog, String addr, String eid, String cno) {
       this.sname = sname;
       this.studlog = studlog;
       this.addr = addr;
       this.eid = eid;
       this.cno = cno;
    }
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public Studlog getStudlog() {
        return this.studlog;
    }
    
    public void setStudlog(Studlog studlog) {
        this.studlog = studlog;
    }
    public String getAddr() {
        return this.addr;
    }
    
    public void setAddr(String addr) {
        this.addr = addr;
    }
    public String getEid() {
        return this.eid;
    }
    
    public void setEid(String eid) {
        this.eid = eid;
    }
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }

    /**
     * @return the photo
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * @param photo the photo to set
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * @return the photo1
     */
    public FormFile getPhoto1() {
        return photo1;
    }

    /**
     * @param photo1 the photo1 to set
     */
    public void setPhoto1(FormFile photo1) {
        this.photo1 = photo1;
    }




}


