package producthiber;
// Generated Dec 20, 2014 12:00:44 AM by Hibernate Tools 3.2.1.GA



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int prodno;
     private String prodname;
     private int price;

    public Product() {
    }

	
    public Product(int prodno) {
        this.prodno = prodno;
    }
    public Product(int prodno, String prodname, int price) {
       this.prodno = prodno;
       this.prodname = prodname;
       this.price = price;
    }
   
    public int getProdno() {
        return this.prodno;
    }
    
    public void setProdno(int prodno) {
        this.prodno = prodno;
    }
    public String getProdname() {
        return this.prodname;
    }
    
    public void setProdname(String prodname) {
        this.prodname = prodname;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


