package com.myapp.struts;
// Generated Jan 20, 2012 11:32:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Item3 generated by hbm2java
 */
import org.apache.struts.upload.FormFile;
public class Item3 extends org.apache.struts.action.ActionForm   implements java.io.Serializable {


     private int itemid;
     private String itemname;
     private double price;
     private String filename;
      private FormFile theFile;

    public Item3() {
    }

	
    public Item3(int itemid) {
        this.itemid = itemid;
    }
    public Item3(int itemid, String itemname, double price, String filename) {
       this.itemid = itemid;
       this.itemname = itemname;
       this.price = price;
       this.filename = filename;
    }
   
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * @return the theFile
     */
    public FormFile getTheFile() {
        return theFile;
    }

    /**
     * @param theFile the theFile to set
     */
    public void setTheFile(FormFile theFile) {
        this.theFile = theFile;
    }




}


