package log;
// Generated Dec 14, 2015 11:58:52 AM by Hibernate Tools 3.2.1.GA



/**
 * Reg generated by hbm2java
 */
public class Reg  implements java.io.Serializable {


     private String uname;
     private Loginn loginn;
     private String addr;
     private String eid;
     private Long cno;

    public Reg() {
    }

	
    public Reg(String uname, Loginn loginn) {
        this.uname = uname;
        this.loginn = loginn;
    }
    public Reg(String uname, Loginn loginn, String addr, String eid, Long cno) {
       this.uname = uname;
       this.loginn = loginn;
       this.addr = addr;
       this.eid = eid;
       this.cno = cno;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public Loginn getLoginn() {
        return this.loginn;
    }
    
    public void setLoginn(Loginn loginn) {
        this.loginn = loginn;
    }
    public String getAddr() {
        return this.addr;
    }
    
    public void setAddr(String addr) {
        this.addr = addr;
    }
    public String getEid() {
        return this.eid;
    }
    
    public void setEid(String eid) {
        this.eid = eid;
    }
    public Long getCno() {
        return this.cno;
    }
    
    public void setCno(Long cno) {
        this.cno = cno;
    }




}


