package log;
// Generated Dec 14, 2015 11:58:52 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Studlog generated by hbm2java
 */
public class Studlog  implements java.io.Serializable {


     private String sname;
     private String pass;
     private Set studregs = new HashSet(0);

    public Studlog() {
    }

	
    public Studlog(String sname) {
        this.sname = sname;
    }
    public Studlog(String sname, String pass, Set studregs) {
       this.sname = sname;
       this.pass = pass;
       this.studregs = studregs;
    }
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getStudregs() {
        return this.studregs;
    }
    
    public void setStudregs(Set studregs) {
        this.studregs = studregs;
    }




}


