package log;
// Generated Dec 14, 2015 11:58:52 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Userlog generated by hbm2java
 */
public class Userlog  implements java.io.Serializable {


     private String uname;
     private String pass;
     private Set userregs = new HashSet(0);

    public Userlog() {
    }

	
    public Userlog(String uname) {
        this.uname = uname;
    }
    public Userlog(String uname, String pass, Set userregs) {
       this.uname = uname;
       this.pass = pass;
       this.userregs = userregs;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getUserregs() {
        return this.userregs;
    }
    
    public void setUserregs(Set userregs) {
        this.userregs = userregs;
    }




}


