package book;
// Generated Jan 4, 2015 8:58:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int bno;
     private Rack rack;
     private String bname;
     private int price;
     private String rackno;

    public Book() {
    }

	
    public Book(int bno) {
        this.bno = bno;
    }
    public Book(int bno, Rack rack, String bname, int price) {
       this.bno = bno;
       this.rack = rack;
       this.bname = bname;
       this.price = price;
    }
   
    public int getBno() {
        return this.bno;
    }
    
    public void setBno(int bno) {
        this.bno = bno;
    }
    public Rack getRack() {
        return this.rack;
    }
    
    public void setRack(Rack rack) {
        this.rack = rack;
    }
    public String getBname() {
        return this.bname;
    }
    
    public void setBname(String bname) {
        this.bname = bname;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * @return the rackno
     */
    public String getRackno() {
        return rackno;
    }

    /**
     * @param rackno the rackno to set
     */
    public void setRackno(String rackno) {
        this.rackno = rackno;
    }




}


