package book;
// Generated Jan 4, 2015 8:58:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rack generated by hbm2java
 */
public class Rack  implements java.io.Serializable {


     private String rackno;
     private String subject;
     private Set books = new HashSet(0);

    public Rack() {
    }

	
    public Rack(String rackno) {
        this.rackno = rackno;
    }
    public Rack(String rackno, String subject, Set books) {
       this.rackno = rackno;
       this.subject = subject;
       this.books = books;
    }
   
    public String getRackno() {
        return this.rackno;
    }
    
    public void setRackno(String rackno) {
        this.rackno = rackno;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


