package com.myapp.struts;
// Generated Jan 13, 2015 3:30:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Logger generated by hbm2java
 */
public class Logger  implements java.io.Serializable {


     private String username;
     private String pass;

    public Logger() {
    }

	
    public Logger(String username) {
        this.username = username;
    }
    public Logger(String username, String pass) {
       this.username = username;
       this.pass = pass;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


