package com.myapp.struts;
// Generated Jan 13, 2015 3:30:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private short rcpno;
     private Stud stud;
     private Byte amt;
     private Date rcpdt;

    public Receipt() {
    }

	
    public Receipt(short rcpno) {
        this.rcpno = rcpno;
    }
    public Receipt(short rcpno, Stud stud, Byte amt, Date rcpdt) {
       this.rcpno = rcpno;
       this.stud = stud;
       this.amt = amt;
       this.rcpdt = rcpdt;
    }
   
    public short getRcpno() {
        return this.rcpno;
    }
    
    public void setRcpno(short rcpno) {
        this.rcpno = rcpno;
    }
    public Stud getStud() {
        return this.stud;
    }
    
    public void setStud(Stud stud) {
        this.stud = stud;
    }
    public Byte getAmt() {
        return this.amt;
    }
    
    public void setAmt(Byte amt) {
        this.amt = amt;
    }
    public Date getRcpdt() {
        return this.rcpdt;
    }
    
    public void setRcpdt(Date rcpdt) {
        this.rcpdt = rcpdt;
    }




}


