package com.myapp.struts;
// Generated Jan 13, 2015 3:30:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stud generated by hbm2java
 */
public class Stud extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private int roll;
     private String name;
     private int age;
     private String doa;
     private Set receipts = new HashSet(0);

    public Stud() {
    }

	
    public Stud(int roll) {
        this.roll = roll;
    }
    public Stud(int roll, String name, int age, String doa, Set receipts) {
       this.roll = roll;
       this.name = name;
       this.age = age;
       this.doa = doa;
       this.receipts = receipts;
    }
   
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getDoa() {
        return this.doa;
    }
    
    public void setDoa(String doa) {
        this.doa = doa;
    }
    public Set getReceipts() {
        return this.receipts;
    }
    
    public void setReceipts(Set receipts) {
        this.receipts = receipts;
    }




}


