package com.myapp.struts;
// Generated May 6, 2015 7:32:34 PM by Hibernate Tools 3.2.1.GA


import java.sql.Blob;
import java.util.Date;
import org.apache.struts.upload.FormFile;

/**
 * Updation generated by hbm2java
 */
public class Updation extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String uname;
     private String pass;
     private String email;
     private String doa;
     private String photo;
     private Blob pic;
     private FormFile photo1;
     private FormFile resume1;

    public Updation() {
    }

	
    public Updation(String uname) {
        this.uname = uname;
    }
    public Updation(String uname, String pass, String email, String doa, String photo, Blob pic) {
       this.uname = uname;
       this.pass = pass;
       this.email = email;
       this.doa = doa;
       this.photo = photo;
       this.pic = pic;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDoa() {
        return this.doa;
    }
    
    public void setDoa(String doa) {
        this.doa = doa;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Blob getPic() {
        return this.pic;
    }
    
    public void setPic(Blob pic) {
        this.pic = pic;
    }

    /**
     * @return the photo1
     */
   /* public FormFile getphoto1() {
        return getPhoto1();
    }

    /**
     * @param photo1 the photo1 to set
     
    public void setphoto1(FormFile photo1) {
        this.setPhoto1(photo1);
    }*/

    /**
     * @return the photo1
     */
    public FormFile getPhoto1() {
        return photo1;
    }

    /**
     * @param photo1 the photo1 to set
     */
    public void setPhoto1(FormFile photo1) {
        this.photo1 = photo1;
    }

    /**
     * @return the resume1
     */
    public FormFile getResume1() {
        return resume1;
    }

    /**
     * @param resume1 the resume1 to set
     */
    public void setResume1(FormFile resume1) {
        this.resume1 = resume1;
    }




}


