package com.myapp.struts;
// Generated Apr 25, 2015 6:16:58 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Chatra generated by hbm2java
 */
public class Chatra extends org.apache.struts.action.ActionForm implements java.io.Serializable  {


     private String roll;
     private String name;
     private int age;
     private String sex;
     private String qualif;
     private int dur;
     private Set qualis = new HashSet(0);

    public Chatra() {
    }

	
    public Chatra(String roll) {
        this.roll = roll;
    }
    public Chatra(String roll, String name, int age, String sex, Set qualis) {
       this.roll = roll;
       this.name = name;
       this.age = age;
       this.sex = sex;
       this.qualis = qualis;
    }
   
    public String getRoll() {
        return this.roll;
    }
    
    public void setRoll(String roll) {
        this.roll = roll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Set getQualis() {
        return this.qualis;
    }
    
    public void setQualis(Set qualis) {
        this.qualis = qualis;
    }

    /**
     * @return the qualif
     */
    public String getQualif() {
        return qualif;
    }

    /**
     * @param qualif the qualif to set
     */
    public void setQualif(String qualif) {
        this.qualif = qualif;
    }

    /**
     * @return the dur
     */
    public int getDur() {
        return dur;
    }

    /**
     * @param dur the dur to set
     */
    public void setDur(int dur) {
        this.dur = dur;
    }




}


