package com.myapp.struts;
// Generated Apr 25, 2015 6:16:58 PM by Hibernate Tools 3.2.1.GA



/**
 * QualiId generated by hbm2java
 */
public class QualiId extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String roll;
     private String qualif;

    public QualiId() {
    }

    public QualiId(String roll, String qualif) {
       this.roll = roll;
       this.qualif = qualif;
    }
   
    public String getRoll() {
        return this.roll;
    }
    
    public void setRoll(String roll) {
        this.roll = roll;
    }
    public String getQualif() {
        return this.qualif;
    }
    
    public void setQualif(String qualif) {
        this.qualif = qualif;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QualiId) ) return false;
		 QualiId castOther = ( QualiId ) other; 
         
		 return ( (this.getRoll().equals(castOther.getRoll())) || ( this.getRoll()!=null && castOther.getRoll()!=null && this.getRoll().equals(castOther.getRoll()) ) )
 && ( (this.getQualif().equals(castOther.getQualif())) || ( this.getQualif()!=null && castOther.getQualif()!=null && this.getQualif().equals(castOther.getQualif()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRoll() == null ? 0 : this.getRoll().hashCode() );
         result = 37 * result + ( getQualif() == null ? 0 : this.getQualif().hashCode() );
         return result;
   }   


}


