package com.myapp.struts;
// Generated Apr 25, 2015 6:16:58 PM by Hibernate Tools 3.2.1.GA



/**
 * Quali generated by hbm2java
 */
public class Quali extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private QualiId id;
     private Chatra chatra;
     private int dur;
     private String roll;

    public Quali() {
    }

	
    public Quali(QualiId id, Chatra chatra) {
        this.id = id;
        this.chatra = chatra;
    }
    public Quali(QualiId id, Chatra chatra, int dur) {
       this.id = id;
       this.chatra = chatra;
       this.dur = dur;
    }
   
    public QualiId getId() {
        return this.id;
    }
    
    public void setId(QualiId id) {
        this.id = id;
    }
    public Chatra getChatra() {
        return this.chatra;
    }
    
    public void setChatra(Chatra chatra) {
        this.chatra = chatra;
    }
    public int getDur() {
        return this.dur;
    }
    
    public void setDur(int dur) {
        this.dur = dur;
    }

    /**
     * @return the roll
     */
    public String getRoll() {
        return roll;
    }

    /**
     * @param roll the roll to set
     */
    public void setRoll(String roll) {
        this.roll = roll;
    }




}


