package com.myapp.struts;
// Generated Jan 27, 2015 9:52:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import org.apache.struts.upload.FormFile;

/**
 * Updation generated by hbm2java
 */
public class Updation extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private String uname;
     private String pass;
     private String email;
     private String doa;
     private String photo;
     private FormFile theFile;

    public Updation() {
    }

	
    public Updation(String uname) {
        this.uname = uname;
    }
    public Updation(String uname, String pass, String email, String doa, String photo) {
       this.uname = uname;
       this.pass = pass;
       this.email = email;
       this.doa = doa;
       this.photo = photo;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDoa() {
        return this.doa;
    }
    
    public void setDoa(String doa) {
        this.doa = doa;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


