package andjava;
// Generated Mar 21, 2016 10:04:54 PM by Hibernate Tools 3.2.1.GA



/**
 * Andlogin generated by hbm2java
 */
public class Andlogin  implements java.io.Serializable {


     private String roll;
     private Andreg andreg;
     private String pass;

    public Andlogin() {
    }

	
    public Andlogin(String roll, Andreg andreg) {
        this.roll = roll;
        this.andreg = andreg;
    }
    public Andlogin(String roll, Andreg andreg, String pass) {
       this.roll = roll;
       this.andreg = andreg;
       this.pass = pass;
    }
   
    public String getRoll() {
        return this.roll;
    }
    
    public void setRoll(String roll) {
        this.roll = roll;
    }
    public Andreg getAndreg() {
        return this.andreg;
    }
    
    public void setAndreg(Andreg andreg) {
        this.andreg = andreg;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


