package com.myapp.struts;
// Generated Jan 27, 2015 7:29:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Loginid generated by hbm2java
 */
public class Loginid extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private String uname;
     private String pass;
     private Set registers = new HashSet(0);

    public Loginid() {
    }

	
    public Loginid(String uname) {
        this.uname = uname;
    }
    public Loginid(String uname, String pass, Set registers) {
       this.uname = uname;
       this.pass = pass;
       this.registers = registers;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getRegisters() {
        return this.registers;
    }
    
    public void setRegisters(Set registers) {
        this.registers = registers;
    }




}


