package com.myapp.struts;
// Generated Jan 27, 2015 7:29:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import org.apache.struts.upload.FormFile;

/**
 * Register generated by hbm2java
 */
public class Register extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int roll;
     private Loginid loginid;
     private String email;
     private String doa;
     private String photo;
     private String uname;
     private String FileName;
     private FormFile theFile;

    public Register() {
    }

	
    public Register(int roll) {
        this.roll = roll;
    }
    public Register(int roll, Loginid loginid, String email, String doa, String photo) {
       this.roll = roll;
       this.loginid = loginid;
       this.email = email;
       this.doa = doa;
       this.photo = photo;
    }
   
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public Loginid getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(Loginid loginid) {
        this.loginid = loginid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDoa() {
        return this.doa;
    }
    
    public void setDoa(String doa) {
        this.doa = doa;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

/*   void setDoa(String format) {
        throw new UnsupportedOperationException("Not yet implemented");
    }*/

    /**
     * @return the theFile
     */
    public FormFile getTheFile() {
        return theFile;
    }

    /**
     * @param theFile the theFile to set
     */
    public void setTheFile(FormFile theFile) {
        this.theFile = theFile;
    }

    /**
     * @return the uname
     */
    public String getUname() {
        return uname;
    }

    /**
     * @param uname the uname to set
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * @return the FileName
     */
    public String getFileName() {
        return FileName;
    }

    /**
     * @param FileName the FileName to set
     */
    public void setFileName(String FileName) {
        this.FileName = FileName;
    }





}


