package noticehiber;
// Generated Dec 22, 2014 10:15:53 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StudNotice generated by hbm2java
 */
public class StudNotice  implements java.io.Serializable {


     private StudNoticeId id;
     private Stud stud;
     private String ntext;
     private Date doa;

    public StudNotice() {
    }

	
    public StudNotice(StudNoticeId id, Stud stud) {
        this.id = id;
        this.stud = stud;
    }
    public StudNotice(StudNoticeId id, Stud stud, String ntext, Date doa) {
       this.id = id;
       this.stud = stud;
       this.ntext = ntext;
       this.doa = doa;
    }
   
    public StudNoticeId getId() {
        return this.id;
    }
    
    public void setId(StudNoticeId id) {
        this.id = id;
    }
    public Stud getStud() {
        return this.stud;
    }
    
    public void setStud(Stud stud) {
        this.stud = stud;
    }
    public String getNtext() {
        return this.ntext;
    }
    
    public void setNtext(String ntext) {
        this.ntext = ntext;
    }
    public Date getDoa() {
        return this.doa;
    }
    
    public void setDoa(Date doa) {
        this.doa = doa;
    }




}


