package noticehiber;
// Generated Dec 22, 2014 10:15:53 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stud generated by hbm2java
 */
public class Stud  implements java.io.Serializable {


     private int roll;
     private String name;
     private Date dob;
     private String pass;
     private String email;
     private Date doa;
     private String photo;
     private String course;
     private String sem;
     private Set studNotices = new HashSet(0);

    public Stud() {
    }

	
    public Stud(int roll) {
        this.roll = roll;
    }
    public Stud(int roll, String name, Date dob, String pass, String email, Date doa, String photo, String course, String sem, Set studNotices) {
       this.roll = roll;
       this.name = name;
       this.dob = dob;
       this.pass = pass;
       this.email = email;
       this.doa = doa;
       this.photo = photo;
       this.course = course;
       this.sem = sem;
       this.studNotices = studNotices;
    }
   
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDoa() {
        return this.doa;
    }
    
    public void setDoa(Date doa) {
        this.doa = doa;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public String getSem() {
        return this.sem;
    }
    
    public void setSem(String sem) {
        this.sem = sem;
    }
    public Set getStudNotices() {
        return this.studNotices;
    }
    
    public void setStudNotices(Set studNotices) {
        this.studNotices = studNotices;
    }




}


