package randoms;
// Generated Feb 19, 2015 7:42:18 PM by Hibernate Tools 3.2.1.GA



/**
 * Tryrandom generated by hbm2java
 */
public class Tryrandom  implements java.io.Serializable {


     private int sno;
     private String value;

    public Tryrandom() {
    }

	
    public Tryrandom(int sno) {
        this.sno = sno;
    }
    public Tryrandom(short sno, String value) {
       this.sno = sno;
       this.value = value;
    }
   
    public int getSno() {
        return this.sno;
    }
    
    public void setSno(int sno) {
        this.sno = sno;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


