package hiberreceipt;
// Generated Dec 22, 2014 10:57:55 AM by Hibernate Tools 3.2.1.GA



/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private int rectno;
     private Stud1 stud1;
     private int amt;
     private int roll;

    public Receipt() {
    }

	
    public Receipt(int rectno) {
        this.rectno = rectno;
    }
    public Receipt(int rectno, Stud1 stud1, int amt) {
       this.rectno = rectno;
       this.stud1 = stud1;
       this.amt = amt;
    }
   
    public int getRectno() {
        return this.rectno;
    }
    
    public void setRectno(int rectno) {
        this.rectno = rectno;
    }
    public Stud1 getStud1() {
        return this.stud1;
    }
    
    public void setStud1(Stud1 stud1) {
        this.stud1 = stud1;
    }
    public int getAmt() {
        return this.amt;
    }
    
    public void setAmt(int amt) {
        this.amt = amt;
    }

    /**
     * @return the roll
     */
    public int getRoll() {
        return roll;
    }

    /**
     * @param roll the roll to set
     */
    public void setRoll(int roll) {
        this.roll = roll;
    }




}


