package hiberreceipt;
// Generated Dec 22, 2014 10:57:55 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Stud1 generated by hbm2java
 */
public class Stud1  implements java.io.Serializable {


     private int roll;
     private String name;
     private int age;
     private Set receipts = new HashSet(0);

    public Stud1() {
    }

	
    public Stud1(int roll) {
        this.roll = roll;
    }
    public Stud1(int roll, String name, int age, Set receipts) {
       this.roll = roll;
       this.name = name;
       this.age = age;
       this.receipts = receipts;
    }
   
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public Set getReceipts() {
        return this.receipts;
    }
    
    public void setReceipts(Set receipts) {
        this.receipts = receipts;
    }




}


