package com.myapp.struts;
// Generated Mar 15, 2013 10:39:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Stud02 generated by hbm2java
 */
public class Stud02 extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private int roll;
     private String name;
     private String doa;
     private String pass;

    public Stud02() {
    }

	
    public Stud02(int roll) {
        this.roll = roll;
    }
    public Stud02(int roll, String name, String doa, String pass) {
       this.roll = roll;
       this.name = name;
       this.doa = doa;
       this.pass = pass;
    }
   
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDoa() {
        return this.doa;
    }
    
    public void setDoa(String doa) {
        this.doa = doa;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


