package com.myapp.struts;
// Generated Feb 26, 2015 6:01:24 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * Login generated by hbm2java
 */
public class Login extends org.apache.struts.action.ActionForm implements java.io.Serializable  {


     private String uname;
     private String pass;
     private Set results = new HashSet(0);
     private Set uregisters = new HashSet(0);

    public Login() {
    }

	
    public Login(String uname) {
        this.uname = uname;
    }
    public Login(String uname, String pass, Set results) {
       this.uname = uname;
       this.pass = pass;
       this.results = results;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * @return the results
     */
    public Set getResults() {
        return results;
    }

    /**
     * @param results the results to set
     */
    public void setResults(Set results) {
        this.results = results;
    }




}


