package com.myapp.struts;
// Generated Feb 26, 2015 6:01:24 PM by Hibernate Tools 3.2.1.GA

import org.apache.struts.upload.FormFile;




/**
 * Question generated by hbm2java
 */
public class Question extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private long qid;
     private Topic topic;
     private String ques;
     private String opt1;
     private String opt2;
     private String opt3;
     private String opt4;
     private String cans;
     private int marks;
     private String clev;
     private String scode;
     private String quesimg;
     private String tcode;
     private int noq;
     
      private FormFile photo1;

    public Question() {
    }

	
    public Question(long qid) {
        this.qid = qid;
    }
    public Question(long qid, Topic topic, String ques, String opt1, String opt2, String opt3, String opt4, String cans, int marks, String clev, String scode, String quesimg) {
       this.qid = qid;
       this.topic = topic;
       this.ques = ques;
       this.opt1 = opt1;
       this.opt2 = opt2;
       this.opt3 = opt3;
       this.opt4 = opt4;
       this.cans = cans;
       this.marks = marks;
       this.clev = clev;
       this.scode = scode;
       this.quesimg = quesimg;
    }
   
    public long getQid() {
        return this.qid;
    }
    
    public void setQid(long qid) {
        this.qid = qid;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }
    public String getQues() {
        return this.ques;
    }
    
    public void setQues(String ques) {
        this.ques = ques;
    }
    public String getOpt1() {
        return this.opt1;
    }
    
    public void setOpt1(String opt1) {
        this.opt1 = opt1;
    }
    public String getOpt2() {
        return this.opt2;
    }
    
    public void setOpt2(String opt2) {
        this.opt2 = opt2;
    }
    public String getOpt3() {
        return this.opt3;
    }
    
    public void setOpt3(String opt3) {
        this.opt3 = opt3;
    }
    public String getOpt4() {
        return this.opt4;
    }
    
    public void setOpt4(String opt4) {
        this.opt4 = opt4;
    }
    public String getCans() {
        return this.cans;
    }
    
    public void setCans(String cans) {
        this.cans = cans;
    }
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }
    public String getClev() {
        return this.clev;
    }
    
    public void setClev(String clev) {
        this.clev = clev;
    }
    public String getScode() {
        return this.scode;
    }
    
    public void setScode(String scode) {
        this.scode = scode;
    }
    public String getQuesimg() {
        return this.quesimg;
    }
    
    public void setQuesimg(String quesimg) {
        this.quesimg = quesimg;
    }

    /**
     * @return the tcode
     */
    public String getTcode() {
        return tcode;
    }

    /**
     * @param tcode the tcode to set
     */
    public void setTcode(String tcode) {
        this.tcode = tcode;
    }

    /**
     * @return the noq
     */
    public int getNoq() {
        return noq;
    }

    /**
     * @param noq the noq to set
     */
    public void setNoq(int noq) {
        this.noq = noq;
    }

    /**
     * @return the photo1
     */
    public FormFile getPhoto1() {
        return photo1;
    }

    /**
     * @param photo1 the photo1 to set
     */
    public void setPhoto1(FormFile photo1) {
        this.photo1 = photo1;
    }

    /**
     * @return the pwa
     */
    



}


