package com.myapp.struts;
// Generated Feb 26, 2015 6:01:24 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String scode;
     private String sname;
     private Set topics = new HashSet(0);

    public Subject() {
    }

	
    public Subject(String scode) {
        this.scode = scode;
    }
    public Subject(String scode, String sname, Set topics) {
       this.scode = scode;
       this.sname = sname;
       this.topics = topics;
    }
   
    public String getScode() {
        return this.scode;
    }
    
    public void setScode(String scode) {
        this.scode = scode;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public Set getTopics() {
        return this.topics;
    }
    
    public void setTopics(Set topics) {
        this.topics = topics;
    }




}


