package com.myapp.struts;
// Generated Feb 26, 2015 6:01:24 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String tcode;
     private Subject subject;
     private String topic;
     private String scode;
     private Set questions = new HashSet(0);

    public Topic() {
    }

	
    public Topic(String tcode) {
        this.tcode = tcode;
    }
    public Topic(String tcode, Subject subject, String topic, Set questions) {
       this.tcode = tcode;
       this.subject = subject;
       this.topic = topic;
       this.questions = questions;
    }
   
    public String getTcode() {
        return this.tcode;
    }
    
    public void setTcode(String tcode) {
        this.tcode = tcode;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }

    /**
     * @return the scode
     */
    public String getScode() {
        return scode;
    }

    /**
     * @param scode the scode to set
     */
    public void setScode(String scode) {
        this.scode = scode;
    }




}


